/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* top =  1  *)
(* src = "../rtl/rca_4bit.v:1.1-15.10" *)
module rca_4bit(A, B, Cin, S, Cout);
  (* src = "../rtl/rca_4bit.v:2.14-2.15" *)
  wire _00_;
  (* src = "../rtl/rca_4bit.v:2.14-2.15" *)
  wire _01_;
  (* src = "../rtl/rca_4bit.v:2.14-2.15" *)
  wire _02_;
  (* src = "../rtl/rca_4bit.v:2.14-2.15" *)
  wire _03_;
  (* src = "../rtl/rca_4bit.v:2.17-2.18" *)
  wire _04_;
  (* src = "../rtl/rca_4bit.v:2.17-2.18" *)
  wire _05_;
  (* src = "../rtl/rca_4bit.v:2.17-2.18" *)
  wire _06_;
  (* src = "../rtl/rca_4bit.v:2.17-2.18" *)
  wire _07_;
  (* src = "../rtl/rca_4bit.v:3.8-3.11" *)
  wire _08_;
  (* src = "../rtl/rca_4bit.v:10.12-10.42|../rtl/full_adder.v:3.9-3.10" *)
  wire _09_;
  (* src = "../rtl/rca_4bit.v:11.12-11.41|../rtl/full_adder.v:3.9-3.10" *)
  wire _10_;
  (* src = "../rtl/rca_4bit.v:12.12-12.41|../rtl/full_adder.v:3.9-3.10" *)
  wire _11_;
  (* src = "../rtl/rca_4bit.v:13.12-13.43|../rtl/full_adder.v:3.12-3.16" *)
  wire _12_;
  (* src = "../rtl/rca_4bit.v:13.12-13.43|../rtl/full_adder.v:3.9-3.10" *)
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  (* src = "../rtl/rca_4bit.v:2.14-2.15" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "../rtl/rca_4bit.v:2.17-2.18" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "../rtl/rca_4bit.v:3.8-3.11" *)
  input Cin;
  wire Cin;
  (* src = "../rtl/rca_4bit.v:5.9-5.13" *)
  output Cout;
  wire Cout;
  (* hdlname = "FA0 A" *)
  (* src = "../rtl/rca_4bit.v:10.12-10.42|../rtl/full_adder.v:2.8-2.9" *)
  wire \FA0.A ;
  (* hdlname = "FA0 B" *)
  (* src = "../rtl/rca_4bit.v:10.12-10.42|../rtl/full_adder.v:2.11-2.12" *)
  wire \FA0.B ;
  (* hdlname = "FA0 Cin" *)
  (* src = "../rtl/rca_4bit.v:10.12-10.42|../rtl/full_adder.v:2.14-2.17" *)
  wire \FA0.Cin ;
  (* hdlname = "FA0 Cout" *)
  (* src = "../rtl/rca_4bit.v:10.12-10.42|../rtl/full_adder.v:3.12-3.16" *)
  wire \FA0.Cout ;
  (* hdlname = "FA0 S" *)
  (* src = "../rtl/rca_4bit.v:10.12-10.42|../rtl/full_adder.v:3.9-3.10" *)
  wire \FA0.S ;
  (* hdlname = "FA1 A" *)
  (* src = "../rtl/rca_4bit.v:11.12-11.41|../rtl/full_adder.v:2.8-2.9" *)
  wire \FA1.A ;
  (* hdlname = "FA1 B" *)
  (* src = "../rtl/rca_4bit.v:11.12-11.41|../rtl/full_adder.v:2.11-2.12" *)
  wire \FA1.B ;
  (* hdlname = "FA1 Cin" *)
  (* src = "../rtl/rca_4bit.v:11.12-11.41|../rtl/full_adder.v:2.14-2.17" *)
  wire \FA1.Cin ;
  (* hdlname = "FA1 Cout" *)
  (* src = "../rtl/rca_4bit.v:11.12-11.41|../rtl/full_adder.v:3.12-3.16" *)
  wire \FA1.Cout ;
  (* hdlname = "FA1 S" *)
  (* src = "../rtl/rca_4bit.v:11.12-11.41|../rtl/full_adder.v:3.9-3.10" *)
  wire \FA1.S ;
  (* hdlname = "FA2 A" *)
  (* src = "../rtl/rca_4bit.v:12.12-12.41|../rtl/full_adder.v:2.8-2.9" *)
  wire \FA2.A ;
  (* hdlname = "FA2 B" *)
  (* src = "../rtl/rca_4bit.v:12.12-12.41|../rtl/full_adder.v:2.11-2.12" *)
  wire \FA2.B ;
  (* hdlname = "FA2 Cin" *)
  (* src = "../rtl/rca_4bit.v:12.12-12.41|../rtl/full_adder.v:2.14-2.17" *)
  wire \FA2.Cin ;
  (* hdlname = "FA2 Cout" *)
  (* src = "../rtl/rca_4bit.v:12.12-12.41|../rtl/full_adder.v:3.12-3.16" *)
  wire \FA2.Cout ;
  (* hdlname = "FA2 S" *)
  (* src = "../rtl/rca_4bit.v:12.12-12.41|../rtl/full_adder.v:3.9-3.10" *)
  wire \FA2.S ;
  (* hdlname = "FA3 A" *)
  (* src = "../rtl/rca_4bit.v:13.12-13.43|../rtl/full_adder.v:2.8-2.9" *)
  wire \FA3.A ;
  (* hdlname = "FA3 B" *)
  (* src = "../rtl/rca_4bit.v:13.12-13.43|../rtl/full_adder.v:2.11-2.12" *)
  wire \FA3.B ;
  (* hdlname = "FA3 Cin" *)
  (* src = "../rtl/rca_4bit.v:13.12-13.43|../rtl/full_adder.v:2.14-2.17" *)
  wire \FA3.Cin ;
  (* hdlname = "FA3 Cout" *)
  (* src = "../rtl/rca_4bit.v:13.12-13.43|../rtl/full_adder.v:3.12-3.16" *)
  wire \FA3.Cout ;
  (* hdlname = "FA3 S" *)
  (* src = "../rtl/rca_4bit.v:13.12-13.43|../rtl/full_adder.v:3.9-3.10" *)
  wire \FA3.S ;
  (* src = "../rtl/rca_4bit.v:4.15-4.16" *)
  output [3:0] S;
  wire [3:0] S;
  (* src = "../rtl/rca_4bit.v:8.6-8.8" *)
  wire c1;
  (* src = "../rtl/rca_4bit.v:8.10-8.12" *)
  wire c2;
  (* src = "../rtl/rca_4bit.v:8.14-8.16" *)
  wire c3;
  sky130_fd_sc_hs__xnor2_1 _41_ (
    .A(_08_),
    .B(_04_),
    .Y(_14_)
  );
  sky130_fd_sc_hs__xnor2_1 _42_ (
    .A(_00_),
    .B(_14_),
    .Y(_09_)
  );
  sky130_fd_sc_hs__maj3_1 _43_ (
    .A(_08_),
    .B(_00_),
    .C(_04_),
    .X(_15_)
  );
  sky130_fd_sc_hs__xnor2_1 _44_ (
    .A(_01_),
    .B(_05_),
    .Y(_16_)
  );
  sky130_fd_sc_hs__xnor2_1 _45_ (
    .A(_15_),
    .B(_16_),
    .Y(_10_)
  );
  sky130_fd_sc_hs__maj3_1 _46_ (
    .A(_01_),
    .B(_05_),
    .C(_15_),
    .X(_17_)
  );
  sky130_fd_sc_hs__xnor2_1 _47_ (
    .A(_02_),
    .B(_06_),
    .Y(_18_)
  );
  sky130_fd_sc_hs__xnor2_1 _48_ (
    .A(_17_),
    .B(_18_),
    .Y(_11_)
  );
  sky130_fd_sc_hs__maj3_1 _49_ (
    .A(_02_),
    .B(_06_),
    .C(_17_),
    .X(_19_)
  );
  sky130_fd_sc_hs__xnor2_1 _50_ (
    .A(_03_),
    .B(_07_),
    .Y(_20_)
  );
  sky130_fd_sc_hs__xnor2_1 _51_ (
    .A(_19_),
    .B(_20_),
    .Y(_13_)
  );
  sky130_fd_sc_hs__maj3_1 _52_ (
    .A(_03_),
    .B(_07_),
    .C(_19_),
    .X(_12_)
  );
  assign \FA3.A  = A[3];
  assign \FA3.B  = B[3];
  assign \FA3.Cin  = c3;
  assign Cout = \FA3.Cout ;
  assign S[3] = \FA3.S ;
  assign \FA2.A  = A[2];
  assign \FA2.B  = B[2];
  assign \FA2.Cin  = c2;
  assign c3 = \FA2.Cout ;
  assign S[2] = \FA2.S ;
  assign \FA1.A  = A[1];
  assign \FA1.B  = B[1];
  assign \FA1.Cin  = c1;
  assign c2 = \FA1.Cout ;
  assign S[1] = \FA1.S ;
  assign \FA0.A  = A[0];
  assign \FA0.B  = B[0];
  assign \FA0.Cin  = Cin;
  assign c1 = \FA0.Cout ;
  assign S[0] = \FA0.S ;
  assign _08_ = Cin;
  assign _00_ = A[0];
  assign _04_ = B[0];
  assign \FA0.S  = _09_;
  assign _01_ = A[1];
  assign _05_ = B[1];
  assign \FA1.S  = _10_;
  assign _02_ = A[2];
  assign _06_ = B[2];
  assign \FA2.S  = _11_;
  assign _03_ = A[3];
  assign _07_ = B[3];
  assign \FA3.S  = _13_;
  assign \FA3.Cout  = _12_;
endmodule
